### PR TITLE
Update dependency glob to v9 Issue 168

### PR DESCRIPTION
**Pull request by crowmw**

### CODE REVIEW

**Comment by AaronMoat** [comment]
Hey @ctalkington, would it be possible to have a look at this one (or similar) in order to fix the aforementioned security vulnerability?

**Comment by hluup** [comment]
I understand that the problem here is the node requirement? As glob 10 requires node version >= 14.17, but archive-utils still supports 12. Is that an hard requirement or could the support for such an old node version be dropped?

**Comment by ctalkington** [comment]
the long term goal is drop older node version support, I've started the process in a few places, just depends on effort level of keeping old working. which becomes high with CVEs coming out often and multiple repository that involved

**Comment by ctalkington** [comment]
closed in favor of https://github.com/archiverjs/archiver-utils/pull/162

this is going to require moving every dependent repo over to node 14 so it may take some time before the result is fully visible

**Pull request closed without merging**
